name: joshsomma.com
description: Personal website of Josh Somma
meta_description: "Personal website of Josh Somma"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://joshsomma.com'
google_analytics: 'UA-11483598-1'
gems:
  - jekyll-paginate
  - jekyll-seo-tag

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Details for the RSS feed generator
url:            'https://www.joshsomma.com'
author:         'Josh'
